Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = "4096"
    v.cpus = "2"
  end

  config.vm.provision "shell", run: "always" do |s|
    s.inline = <<PEASSET
      (test -e /vagrant/pe.tar.gz && mv /vagrant/pe.tar.gz /tmp/) || true
PEASSET
    end
  config.vm.provision "shell", path: "../../terraform/aws/templates/pe_master_bootstrap.sh.tpl"
end
